package chubiang.config

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer

class SecurityWebApplicationInitializer: AbstractSecurityWebApplicationInitializer()